library(rgeos)
library(maptools)
library(data.table)
library(fullPage) # remotes::install_github("RinteRface/fullPage")
library(shiny)
library(echarts4r)
library(leaflet)

### these rds files are generated by data_prepare.R 

age_loc_counts <- readRDS("age_loc_counts.rds")
age_year_counts <- readRDS("age_year_counts.rds")
age_loc2_counts <- readRDS("age_loc2_counts.rds")
year_date_counts <- readRDS("year_date_counts.rds")
inj_loc2_counts <- readRDS("inj_loc2_counts.rds")
melb_mapdat_copy <- readRDS("melb_mapdat_copy.rds")

# Introduction Page content
md1 <- "
    # An Analysis of Road Accidents in Victoria
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    The aim is to provide an overiew of road accidents in Victoria and analyse 
    which age group would contribute most to car accidents.
    "

# About page content
md2 <- "
    # About

    ## &nbsp; Road Accidents Data 

    &emsp; The graphes in the data exploration:
    <br><br>

    - Accidents Choropleths in Victoria
    <br>
    
    - Correlation between Accidents and Age by Year
    <br>
    
    - Correlation between Accidents and Age by Area
    <br>
    
    "

# Map Page content
md_map <- "
    <br/><br/><br/><br/><br/><br/>
    # Opeations:
    Click the area of map  
    <br/>Hover over the region
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    # Details:
    The map demonstrates an overview of the accidents happened in Victoria from 2006 to 2020.
    The Nightingale's Rose Diagram demonstrates an overview of number of accidents by age group.
    <br/><br/><br/>
    According to the map, the metropolitan Melbourne can have a higher rate of car accidents, 
    while town cities are also having a great ratio of accidents in regional areas. 
    "

# By year page content
md_by_year <- "
    <br/><br/><br/><br/><br/><br/>
    # Opeations:
    Click the select year to change the year of data
    <br/>Hover over to show more details
    <br/>lick male/female icon to select data
    
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    # Details:
    The regression model demonstrates the correlation between the number of accidents and age. 
    It could be categorised by different gender.
    The heat map demonstrates the number of accidents divided by weekdays in each month of each year. 
    <br/><br/><br/>
    Female results more car accidents than male among all age groups. 
    The peak of number of accidents is around 30-year-old, younger people (below 30 years old) 
    cause many accidents indeed, but the group in between 30-40 years old has 
    also contributed a large number of car accidents.
    "

# By area page content
md_by_urban <- "
    <br/><br/><br/><br/><br/><br/>
    # Opeations:
    Click the select area to change the area that data represents
    <br/>Hover over to show more details
    
    <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    # Details:
    The regression model demonstrates the correlation between the number of accidents and age.
    The Nightingale's Rose Diagram demonstrates the injured level in different area.
    <br/><br/><br/>
    "

# Reference Page content
md3 <- "
    # &nbsp; Road Accidents Data 
    <br/><br/><br/><br/>
    &emsp; The data is collected form:
    <br/><br/>
    &emsp; &emsp; VicRoad:
    <br/>
    &emsp; &emsp; https://vicroadsopendatastorehouse.vicroads.vic.gov.au/opendata/Road_Safety/ACCIDENT.zip
    <br/><br/>
    &emsp; &emsp; RACV:
    <br/>
    &emsp; &emsp; https://www.racv.com.au/content/dam/racv/images/public-policy/reports/RACV%20Young%20Adult%20Licensing%20Trends%202017.pdf
    "


ui <- pagePiling(
  # center = TRUE,
  tags$head(
    tags$style(HTML(".leaflet-container { background: #313131; }"))
  ),
  sections.color = rep("#313131", 10),
  # navigation = TRUE,
  menu = c(
    "Introduction" = "intro",
    "About" = "about",
    "Map" = "map",
    "By Year" = "by_year",
    "By Area" = "by_urban",
    "Reference" = "ref"
  ),
  # set the background
  pageSectionImage(
    # will not show in viewer, open in browser
    menu = "intro",
    center = TRUE,
    img = "https://www.supercars.net/blog/wp-content/uploads/2020/03/img_14-scaled.jpeg",
    div(markdown(md1), style = "color:#f3f3f3;")
  ),
  pageSectionImage(
    menu = "about",
    img = "https://www.supercars.net/blog/wp-content/uploads/2020/03/img_14-scaled.jpeg",
    pageColumn(
      width = 12,
      div(markdown(md2), style = "color:#f3f3f3;")
    )
  ),
  pageSection(
    menu = "map",
    pageColumn(
      width = 3,
      div(markdown(md_map), style = "color:#f3f3f3;")
    ),
    pageColumn(
      width = 9,
      leafletOutput("leaf1", height = 450),
      echarts4rOutput("echarts1")
    )
  ),
  pageSection(
    menu = "by_year",
    pageColumn(
      width = 3,
      div(markdown(md_by_year), style = "color:#f3f3f3;")
    ),
    pageColumn(
      width = 9,
      selectInput(
        "select1",
        shiny::HTML("<p><span style='color: white'>Select Year:</span></p>"),
        choices = sort(unique(age_year_counts$year_), decreasing = TRUE)
      ),
      echarts4rOutput("echarts2", height = "300px"),
      echarts4rOutput("echarts3")
    )
  ),
  pageSection(
    menu = "by_urban",
    pageColumn(
      width = 3,
      div(markdown(md_by_urban), style = "color:#f3f3f3;")
    ),
    pageColumn(
      width = 9,
      selectInput(
        "select2",
        shiny::HTML("<p><span style='color: white'>Select Area:</span></p>"),
        choices = sort(unique(age_loc2_counts$DEG_URBAN_NAME))
      ),
      echarts4rOutput("echarts4", height = "300px"),
      echarts4rOutput("echarts5")
    )
  ),
  pageSection(
    menu = "ref",
    div(markdown(md3), style = "color:#f3f3f3;")
  )
)


# server side
server <- function(input, output) {
  
  # Choropleth chart using leaflet
  output$leaf1 <- renderLeaflet({
    labels <- sprintf(
      "<strong>%s</strong><br/>Accidengts: %s",
      melb_mapdat_copy$LGA_NAME, melb_mapdat_copy$N
    ) %>% lapply(htmltools::HTML)
    pal <- colorBin("YlOrRd", melb_mapdat_copy$N, bins = c(0, 10, 100, 500, 1000, 2000, 5000, 10000, Inf))
    
    # title
    tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    left: 50%;
    text-align: center;
    padding-left: 10px; 
    padding-right: 10px; 
    background: #313131;
    color: #f3f3f3;
    font-weight: bold;
    font-size: 28px;
  }"))
    
    title <- tags$div(
      tag.map.title, HTML("Accidents Choropleths in Victoria")
    )  
    
    # Set leaflet map
    leaflet(melb_mapdat_copy, 
            options = leafletOptions(zoomControl = FALSE)) %>%
      addPolygons(
        layerId = ~LGA_NAME,
        fillColor = ~ pal(N),
        weight = 2,
        opacity = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.7,
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE
        ),
        label = labels,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto"
        )
      ) %>%
      addLegend(
        pal = pal,
        values = ~N,
        position = "bottomright"
      ) %>% 
      addControl(title, position = "topleft", className="map-title")
  })
  
  # Nightingale's Rose Diagram
  output$echarts1 <- renderEcharts4r({
    req(input$leaf1_shape_click$id)
    # browser()
    p_dat <- age_loc_counts[LGA_NAME == input$leaf1_shape_click$id][order(-N)]
    # calculate percentage
    p_dat[, percent_ := round(N/sum(N) * 100, 1)]
    # build the chart
    p_dat %>%
      e_charts(`Age Group`) %>%
      e_pie(N, roseType = "radius", name = "Number of Accidents") %>%
      e_title(sprintf("Number of Accidents by Age Group in %s", input$leaf1_shape_click$id), left = "center") %>%
      e_tooltip(formatter = htmlwidgets::JS("
      function(params){
        return(params.name + '<br />Number of Accidents: ' + params.value + '(' + params.percent + '%)')
      }
    ")) %>%
      # add theme and legend
      e_theme("dark-bold") %>% 
      e_legend(top = "bottom")
  })
  
  # scatter chart with loess regression
  output$echarts2 <- renderEcharts4r({
    # browser()
    req(input$select1)
    # modify the table to add number of accidents
    p_dat <- age_year_counts[year_ == input$select1][SEX %in% c("F", "M")][order(-N)]
    # set the name of new columns
    setnames(p_dat, old = "N", new = "Number of Accidents")
    # create regression model
    p_dat %>%
      group_by(`SEX`) %>%
      e_charts(AGE) %>%
      e_scatter(`Number of Accidents`) %>%
      e_loess(
        `Number of Accidents` ~ `AGE`,
        smooth = TRUE,
        showSymbol = FALSE,
        legend = FALSE
      ) %>%
      # title name
      e_title("Correlation between Accidents and Age by Gender") %>%
      e_y_axis(min = 0) %>%
      e_tooltip(axisPointer = list(type = "cross")) %>%
      e_theme("dark-bold") %>% 
      # set y axis
      e_y_axis(
        name = "Number of Accidents",
        splitLine = list(
          lineStyle = list(
            type = "dashed"
          )
        ),
        axisLine = list(
          show = FALSE
        ),
        axisTick = list(
          show = FALSE
        )
      ) %>%
      # set x axis
      e_x_axis(
        name = "Age",
        min = 16,
        max = 90,
        splitLine = list(
          show = FALSE
        ),
        axisLine = list(
          show = FALSE
        ),
        axisTick = list(
          show = FALSE
        )
      ) %>% 
      e_legend(top = "bottom")
  })
  
  # calendar heat map
  output$echarts3 <- renderEcharts4r({
    req(input$select1)
    # browser()
    p_dat <- year_date_counts[year_ == input$select1]
    n_limits <-
      as.integer(quantile(p_dat$N, probs = c(0.1, 0.9), na.rm = TRUE))
    
    # create a heat map
    p_dat %>%
      e_charts(ACCIDENTDATE) %>%
      e_calendar(range = input$select1, 
                 monthLabel = list(color = "white"),
                 dayLabel = list(color = "white")) %>%
      e_heatmap(N, coord_system = "calendar", name = "Number of Accidents") %>%
      e_visual_map(min = n_limits[1], max = n_limits[2]) %>%
      e_title("Accidents Heatmap by Date") %>%
      e_tooltip("item") %>%
      e_theme("dark-bold")
  })
  
  # scatter chart with loess regression, the step is similar to the last regression model.
  output$echarts4 <- renderEcharts4r({
    # browser()
    req(input$select2)
    p_dat <-
      age_loc2_counts[DEG_URBAN_NAME == input$select2][order(-N)]
    setnames(p_dat, old = "N", new = "Number of Accidents")
    p_dat %>%
      e_charts(`AGE`) %>%
      e_scatter(`Number of Accidents`) %>%
      e_loess(
        `Number of Accidents` ~ `AGE`,
        smooth = TRUE,
        showSymbol = FALSE,
        legend = FALSE
      ) %>%
      # title name
      e_title("Correlation between Accidents and Age") %>%
      e_y_axis(min = 0) %>%
      e_tooltip(axisPointer = list(type = "cross")) %>%
      e_theme("dark-bold") %>% 
      # set y axis
      e_y_axis(
        name = "Number of Accidents",
        splitLine = list(
          lineStyle = list(
            type = "dashed"
          )
        ),
        axisLine = list(
          show = FALSE
        ),
        axisTick = list(
          show = FALSE
        )
      ) %>%
      # set x axis
      e_x_axis(
        name = "Age",
        min = 16,
        max = 90,
        splitLine = list(
          show = FALSE
        ),
        axisLine = list(
          show = FALSE
        ),
        axisTick = list(
          show = FALSE
        )
      ) %>% 
      e_legend(top = "bottom")
  })
  
  # Nightingale's Rose Diagram
  output$echarts5 <- renderEcharts4r({
    # browser()
    req(input$select2)
    p_dat <- inj_loc2_counts[DEG_URBAN_NAME == input$select2][order(-N)]
    p_dat[, percent_ := round(N/sum(N) * 100, 1)]
    p_dat %>%
      e_charts(`Inj Level Desc`) %>%
      e_pie(N, roseType = "radius", name = "Number of Accidents") %>%
      e_title(sprintf("Number of Accidents by Inj Level among %s", input$select2), left = "center") %>%
      e_tooltip(formatter = htmlwidgets::JS("
      function(params){
        return(params.name + '<br />Number of Accidents: ' + params.value + '(' + params.percent + '%)')
      }
    ")) %>%
      e_theme("dark-bold") %>% 
      e_legend(top = "bottom")
  })
}

shinyApp(ui, server)
